name: Run AWS Spec tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-aws-test-kitchen:
    uses: hutchic-observe-meta/aws-test-kitchen-public/.github/workflows/ci.yml@main
    with:
      test_type: cloudformation
      code_sha: ${{ github.sha }}
